FORMAT: 1A
HOST: http://polls.apiblueprint.org/


# apisearch

Full text search service which communicates through JSON API.


### Data Structures

#### Settings
- feedUrl: `http://shop.tld/feed.xml` (string, required) - url of data feed
- feedFormat: `heureka` (enum[string], required)
    - `heureka`
    - `zbozi`
    - `google`
    - `json`

#### Product
- id: `1` (string, required) - ID of product
- userId: `1` (int, required) - ID of user
- name: `Postel bílá` (string, required) - Name of product
- description: `Postel bílá vyrobena z masivu.` (string, required) - Description of product
- url: `http://domain.tld/1` (string, required) - URL of product detail
- img: `http://domain.tld/1.jpg` (string, required) - URL of product's image
- price: `1` (int, required) - Price of product
- updated: `2016-12-04T23:22:16+01:00` (string, required) - Timestamp of last update


## Status [/api/v1/status]

### Healthz [GET /api/v1/status/healthz]
+ Response 200 (application/json)


## Settings [/api/v1/settings/{userId}]

### Get user's settings [GET]
+ Response 200 (application/json)
    + Attributes (Settings, required)
+ Response 400 (application/json)

### Store user's settings [POST]
+ Request
    + Attributes (Settings, required)
+ Response 200 (application/json)
+ Response 500 (application/json)

### Delete user's settings [DELETE]
+ Response 200 (application/json)
+ Response 400 (application/json)


## Search [/api/v1/search{?query}]

### Fulltext search [GET]
+ Parameters
    + q: `postel` (string, required) - searched query
    + userId: `1` (int, required) - user id
+ Response 200 (application/json)
    + Attributes
        + products (array[Product], required)
+ Response 400 (application/json)
+ Response 503 (application/json)
